language: scala

jdk:
  - oraclejdk11

scala:
  - 2.13.3

before_install:
  - wget https://downloads.lightbend.com/scala/2.13.3/scala-2.13.3.tgz
  - tar xzf scala-2.13.3.tgz
  - PATH=${PATH}:scala-2.13.3/bin

script:
  - scala -version
  - ./gradlew buildDependents
  - ./gradlew test
  - bash bin/test.sh
